### ISSUE TITLE
Last sync on server was 3 days ago (26 Jul 2018 14:56:21)

### ISSUE THREAD

**Issue by agasigp** [IndraGunawan/packagist-mirror#2]
![photo_2018-07-29_17-38-11](https://user-images.githubusercontent.com/2476867/43365377-485b8f8a-9356-11e8-84cb-5ff9b6f5d572.jpg)
Something is wrong with the server. Last sync was 3 days ago.

**Comment by IndraGunawan** [comment]
the issue has been fixed
