### ISSUE TITLE
mirror a satis (composer repository)

### ISSUE THREAD

**Issue by tawfekov** [IndraGunawan/packagist-mirror#4]
Hi,
I'd like to know the steps to mirror a satis repo (https://satis.oroinc.com/) ? can you please guide me through it ?

**Comment by tawfekov** [comment]
as far as I see changing  https://github.com/IndraGunawan/packagist-mirror/blob/master/src/Command/DumpMetadataCommand.php#L53 is making it , I think its good point to refactor , right ?

**Comment by IndraGunawan** [comment]
hi @tawfekov 
you're right.
could you send PR for that?

**Comment by tawfekov** [comment]
Hi @IndraGunawan ,

I've create the pull request #5
