### ISSUE TITLE
Error when installing GuzzleHttp\Guzzle

### ISSUE THREAD

**Issue by budihaa** [IndraGunawan/packagist-mirror#7]
When i tried to install GuzzleHttp with composer this message showed up.

`[Composer\Repository\RepositorySecurityException]                                                                                                                                       The contents of https://packagist.phpindonesia.id/p/illuminate/auth%242bc0847e47354e9739af7cbe831f392cfc8fb56d90b2d31b3750df86c3951628.json do not match its signature. This could in  dicate a man-in-the-middle attack or e.g. antivirus software corrupting files. Try running composer again and report this if you think it is a mistake.`

I've tried to disable the windows defender and still got those error.

**Comment by IndraGunawan** [comment]
Hi, sorry for late response.
please try again
